require("sahil.plugins-setup")
require("sahil.core.options")
require("sahil.core.keymaps")
require("sahil.core.colorscheme")
require("sahil.plugins.comment")
require("sahil.plugins.nvim-tree")
require("sahil.plugins.lualine")
require("sahil.plugins.telescope")
require("sahil.plugins.nvim-cmp")
require("sahil.plugins.lsp.mason")
require("sahil.plugins.lsp.lspsaga")
require("sahil.plugins.lsp.lspconfig")
require("sahil.plugins.lsp.null-ls")
require("sahil.plugins.autopairs")
require("sahil.plugins.gitsigns")
require("sahil.plugins.treesitter")
require("sahil.plugins.harpoon")
require("sahil.plugins.toggleterm")
require("sahil.plugins.indentation")
require("sahil.plugins.nvim-colorizer")
require("sahil.plugins.dap")
-- vim.o.background = "dark" -- or "light" for light mode
-- vim.cmd([[colorscheme gruvbox]])
