--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sahil/archives/pictures/wallpapers/ddd.jpg"

-- Special
background="#000103"
foreground="#bfbfc0"
cursor="#bfbfc0"

-- Colors
color0="#000103"
color1="#06496F"
color2="#075988"
color3="#086497"
color4="#0972AC"
color5="#077FC4"
color6="#0C83BB"
color7="#bfbfc0"
color8="#3f4042"
color9="#06496F"
color10="#075988"
color11="#086497"
color12="#0972AC"
color13="#077FC4"
color14="#0C83BB"
color15="#bfbfc0"
