--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sahil/repos/config/wallpapers/road.jpg"

-- Special
background="#020203"
foreground="#bfbfc0"
cursor="#bfbfc0"

-- Colors
color0="#020203"
color1="#505567"
color2="#37638A"
color3="#546B90"
color4="#6A7596"
color5="#8A778D"
color6="#7187A9"
color7="#bfbfc0"
color8="#414142"
color9="#505567"
color10="#37638A"
color11="#546B90"
color12="#6A7596"
color13="#8A778D"
color14="#7187A9"
color15="#bfbfc0"
