# Shell variables
# Generated by 'wal'
wallpaper="/home/sahil/archives/pictures/wallpapers/ddd.jpg"

# Special
background='#000103'
foreground='#bfbfc0'
cursor='#bfbfc0'

# Colors
color0='#000103'
color1='#06496F'
color2='#075988'
color3='#086497'
color4='#0972AC'
color5='#077FC4'
color6='#0C83BB'
color7='#bfbfc0'
color8='#3f4042'
color9='#06496F'
color10='#075988'
color11='#086497'
color12='#0972AC'
color13='#077FC4'
color14='#0C83BB'
color15='#bfbfc0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
