--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sahil/repos/config/wallpapers/second.jpg"

-- Special
background="#000104"
foreground="#bfbfc0"
cursor="#bfbfc0"

-- Colors
color0="#000104"
color1="#1B4454"
color2="#2C4A56"
color3="#3A5A62"
color4="#4D5055"
color5="#666665"
color6="#8B443F"
color7="#bfbfc0"
color8="#3f4042"
color9="#1B4454"
color10="#2C4A56"
color11="#3A5A62"
color12="#4D5055"
color13="#666665"
color14="#8B443F"
color15="#bfbfc0"
