# Shell variables
# Generated by 'wal'
wallpaper="/home/sahil/repos/config/wallpapers/second.jpg"

# Special
background='#000104'
foreground='#bfbfc0'
cursor='#bfbfc0'

# Colors
color0='#000104'
color1='#1B4454'
color2='#2C4A56'
color3='#3A5A62'
color4='#4D5055'
color5='#666665'
color6='#8B443F'
color7='#bfbfc0'
color8='#3f4042'
color9='#1B4454'
color10='#2C4A56'
color11='#3A5A62'
color12='#4D5055'
color13='#666665'
color14='#8B443F'
color15='#bfbfc0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
