# Shell variables
# Generated by 'wal'
wallpaper="/home/sahil/repos/config/wallpapers/road.jpg"

# Special
background='#020203'
foreground='#bfbfc0'
cursor='#bfbfc0'

# Colors
color0='#020203'
color1='#505567'
color2='#37638A'
color3='#546B90'
color4='#6A7596'
color5='#8A778D'
color6='#7187A9'
color7='#bfbfc0'
color8='#414142'
color9='#505567'
color10='#37638A'
color11='#546B90'
color12='#6A7596'
color13='#8A778D'
color14='#7187A9'
color15='#bfbfc0'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
